name: call build workflw

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: "web-app"
      environment: "staging"
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
  
  print-version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print build version
        run: |
          echo "Build version: ${{ needs.build.outputs.build_version }}"
