# Workflow name
name: hello workflow

# Trigger the workflow on every push
on:
  workflow_dispatch: 

# Jobs inside the workflow
jobs:
   
# job name
   greet:
      runs-on: ubuntu-latest # github runner
      steps:
        - name: say hello
          run: echo "Hello"

        - name: say hello to user
          run: echo "Hello $USER"

        - name: print current date and time
          run: date

        - name: print branch name
          run: | 
            echo "Trigger by branch: ${{ github.ref_name }}"

# Every job need a runner
# Runner: github runner,self hosted runner

# Workflow -->Jobs--> Steps



# Every job need a runner
# Runner: github runner,self hosted runner

# Workflow -->Jobs--> Steps
